# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('MATTEL', 'Mattel'), ('CHINGUITEL', 'Chinguitel'), ('MAURITEL', 'Mauritel')], max_length=20)),
                ('phone_number', models.CharField(help_text='The 8-digit Mauritanian number to top up (2,3,4 prefixes).', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference', models.CharField(help_text='Unique transaction reference for audit tracking.', max_length=64, unique=True)),
                ('idempotency_key', models.CharField(help_text='Prevents double processing of the same top-up request.', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Top-up',
                'verbose_name_plural': 'Top-ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
