# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official agent name or kiosk name.', max_length=100)),
                ('location', models.CharField(help_text='Physical address or area (e.g., Tevragh Zeina).', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CASHIN', 'Cash In'), ('CASHOUT', 'Cash Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of money handled in MRU.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('token', models.CharField(help_text='Unique 8-digit verification code (used for cash-out).', max_length=8, unique=True)),
                ('reference', models.CharField(help_text='Unique transaction reference for audit tracking.', max_length=64, unique=True)),
                ('idempotency_key', models.CharField(help_text='Prevents double processing of the same cash operation.', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent Transaction',
                'verbose_name_plural': 'Agent Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
