# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(help_text='Linked user account for this agent.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='agent',
            field=models.ForeignKey(help_text='The agent performing this operation.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet involved in this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_transactions', to='wallet.wallet'),
        ),
    ]
