# Generated by Django 5.2.7 on 2025-11-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttransaction",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="The agent performing this operation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="agents.agent",
            ),
        ),
    ]
