# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('TRANSFER', 'Wallet Transfer'), ('TOPUP', 'Mobile Top-up'), ('BILLPAY', 'Bill Payment'), ('CASHIN', 'Cash In'), ('CASHOUT', 'Cash Out'), ('AGENT_COMMISSION', 'Agent Commission')], max_length=30, unique=True)),
                ('rate_percent', models.DecimalField(decimal_places=3, help_text='Percentage (e.g. 1.500 = 1.5%)', max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat fee in MRU, added to the percentage fee.', max_digits=10)),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Rule',
                'verbose_name_plural': 'Fee Rules',
                'ordering': ['operation'],
            },
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fees.feerule')),
            ],
            options={
                'verbose_name': 'Fee Transaction',
                'verbose_name_plural': 'Fee Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
