# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('INTERNET', 'Internet'), ('TV', 'Television'), ('OTHER', 'Other')], max_length=20)),
                ('provider_name', models.CharField(help_text='Bill provider name, e.g., SOMELEC, Mauritel.', max_length=100)),
                ('account_number', models.CharField(help_text='User’s account ID at the provider.', max_length=30)),
                ('customer_name', models.CharField(help_text='Name of the bill owner or subscriber.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bill amount in MRU.', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference', models.CharField(help_text='Unique payment reference.', max_length=64, unique=True)),
                ('idempotency_key', models.CharField(help_text='Prevents double payment processing.', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
