# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='wallet',
            field=models.ForeignKey(help_text='The wallet from which this bill is paid.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='wallet.wallet'),
        ),
    ]
