# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='receiver_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='wallet.wallet'),
        ),
    ]
