# Generated by Django 5.2.7 on 2025-10-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simplekyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simple_kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simplekyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
